[package]
name = 'Nessie'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'Nessie'

[dependencies]
extendr-api = '*'
integrate = "0.1.11"
kiddo = "5.0.3"
libm = "0.2.15"
ndarray = "0.16.1"
rayon = "1.10.0"
roots = "0.0.8"
