# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Nessie_wrappers", use_symbols = TRUE, package_name = "Nessie")

#' @usage NULL
#' @useDynLib Nessie, .registration = TRUE
NULL

#' Calculates multiple comoving distances for multiple redshifts.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM)
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM)
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM)
#' @param hubble_constant H0 = 100 * h
#' @return multiple comoving distance in Mpc.
#' @export
comoving_distances_at_z <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distances_at_z, redshift_array, omega_m, omega_k, omega_l, h0)

#' redshift at some given comoving distances in Mpc
#' @export
z_at_comoving_distances <- function(distances, omega_m, omega_k, omega_l, h0) .Call(wrap__z_at_comoving_distances, distances, omega_m, omega_k, omega_l, h0)

#' finding the links between all galaxies
#' @description
#' `fof_links` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc. 
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled. 
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)

#' finding the links between all galaxies in a brute force way.
#' @description
#' `fof_link_brutal` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc. 
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled. 
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links_brute_force <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links_brute_force, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)

#' finding the links between all galaxies in a brute force way.
#' @description
#' `fof_link_brutal` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc. 
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled. 
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links_aaron <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links_aaron, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)


# nolint end
