# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Nessie_wrappers", use_symbols = TRUE, package_name = "Nessie")

#' @usage NULL
#' @useDynLib Nessie, .registration = TRUE
NULL

#' Calculates multiple comoving distances for multiple redshifts.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM)
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM)
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM)
#' @param hubble_constant H0 = 100 * h
#' @return multiple comoving distance in Mpc.
#' @export
comoving_distances_at_z <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distances_at_z, redshift_array, omega_m, omega_k, omega_l, h0)

#' redshift at some given comoving distances in Mpc
#' @export
z_at_comoving_distances <- function(distances, omega_m, omega_k, omega_l, h0) .Call(wrap__z_at_comoving_distances, distances, omega_m, omega_k, omega_l, h0)

#' finding the links between all galaxies in a brute force way.
#' @description
#' `fof_link_aaron` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc. 
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled. 
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links_aaron <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links_aaron, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)

#' Creates a group catalog from the given arrays.
#' @description
#' This is the R wrapper for the rust functionality that builds the group catalog. There shouldn't
#' be a need to use this in R as a more R-friendly function should be available.
#' @param ra Array of right asscension values. 
#' @param dec Array of declination values.
#' @param redshift Array of redshift values.
#' @param magnitudes Array of apparent magnitude values.
#' @param velocity_errors Array of velocity errors. 
#' @param group_id Array of the group ids, where -1 represents galaxies not in a group.
#' @return A named list with ra, dec, redshift, co_dist, r50, r100, rsigma, and multiplicity.
create_group_catalog <- function(ra, dec, redshift, magnitudes, velocity_errors, group_ids, omega_m, omega_k, omega_l, h0) .Call(wrap__create_group_catalog, ra, dec, redshift, magnitudes, velocity_errors, group_ids, omega_m, omega_k, omega_l, h0)


# nolint end
