# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Nessie_wrappers", use_symbols = TRUE, package_name = "Nessie")

#' @usage NULL
#' @useDynLib Nessie, .registration = TRUE
NULL

#' Calculates multiple comoving distances for multiple redshifts.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @return multiple comoving distance in Mpc.
#' @export
comoving_distances_at_z <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distances_at_z, redshift_array, omega_m, omega_k, omega_l, h0)

#' Redshift at some given comoving distances in Mpc.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @export
z_at_comoving_distances <- function(distances, omega_m, omega_k, omega_l, h0) .Call(wrap__z_at_comoving_distances, distances, omega_m, omega_k, omega_l, h0)

#' Distance modulus.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @returns The distance modulus for the given array of redshifts.
#' @export
distance_modulus <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__distance_modulus, redshift_array, omega_m, omega_k, omega_l, h0)

#' Calculate the hubble constant at different redshifts.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @returns Multiple H(z) for different z.
#' @export
h_at_z <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__h_at_z, redshift_array, omega_m, omega_k, omega_l, h0)

#' Calculate the Rvir from a given mass for a range of redshift values.
#' @param max_solar_mass The maximum viral mass in solar masses for the viral radii.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @export
calculate_max_rvirs <- function(max_solar_mass, redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__calculate_max_rvirs, max_solar_mass, redshift_array, omega_m, omega_k, omega_l, h0)

#' Calculate the Sigma from a given mass for a range of redshift values.
#' @param max_solar_mass The maximum viral mass in solar masses for the viral radii.
#' @param redshift_array an array of multiple redshift values.
#' @param omega_m Mass density (often 0.3 in LCDM).
#' @param omega_k Effective mass density of relativistic particles (often 0. in LCDM).
#' @param omega_l Effective mass density of dark energy (often 0.7 in LCDM).
#' @param h0 H0 = 100 * h.
#' @export
calculate_max_sigmas <- function(max_solar_mass, redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__calculate_max_sigmas, max_solar_mass, redshift_array, omega_m, omega_k, omega_l, h0)

#' finding the links between all galaxies in a brute force way.
#' @description
#' `fof_links_aaron` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc.
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled.
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links_aaron <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links_aaron, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)

#' finding the links between all galaxies in a brute force way.
#' @description
#' `fof_links_fast` will determine all connections between galaxies in a survey and return the pairs.
#' @param ra Array of right ascension values.
#' @param dec Array of declination values.
#' @param comoving_distances Array of comoving distances in Mpc.
#' @param linking_lengths An array of individual scaled linking lengths for each galaxy (ignoring r0 and b0).
#' @param b0 The plane-of-sky constant to be scaled.
#' @param r0 The line-of-sight constant to be scaled.
#' @return A dataframe-like object of tuples which represent the link between galaxies (i, j) if they exist.
#' @export
fof_links_fast <- function(ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los) .Call(wrap__fof_links_fast, ra_array, dec_array, comoving_distances, linking_lengths_pos, linking_lengths_los)

#' Creates a group catalog from the given arrays.
#' @description
#' This is the R wrapper for the rust functionality that builds the group catalog. There shouldn't
#' be a need to use this in R as a more R-friendly function should be available.
#' @param ra Array of right asscension values.
#' @param dec Array of declination values.
#' @param redshift Array of redshift values.
#' @param magnitudes Array of apparent magnitude values.
#' @param velocity_errors Array of velocity errors.
#' @param group_id Array of the group ids, where -1 represents galaxies not in a group.
#' @return A named list with group properties.
#' @export
create_group_catalog <- function(ra, dec, redshift, absolute_magnitudes, velocity_errors, group_ids, omega_m, omega_k, omega_l, h0) .Call(wrap__create_group_catalog, ra, dec, redshift, absolute_magnitudes, velocity_errors, group_ids, omega_m, omega_k, omega_l, h0)

#' Determines the s score as in Robotham+2011
#' @export
calculate_s_score <- function(measured_groups, mock_groups, min_group_size) .Call(wrap__calculate_s_score, measured_groups, mock_groups, min_group_size)

#' The Harmoic Mean
#' @param values The array of objects of which to find the harmonic mean
#' @returns The harmonic mean.
#' @export
calculate_harmonic_mean <- function(values) .Call(wrap__calculate_harmonic_mean, values)

#' Creates a pair catalog from the given arrays.
#' @description
#' This is the R wrapper for the rust functionality that builds the pair catalog. There shouldn't
#' be a need to use this in R as a more R-friendly function should be available.
#' @param ra Array of right asscension values.
#' @param dec Array of declination values.
#' @param redshift Array of redshift values.
#' @param magnitudes Array of apparent magnitude values.
#' @param group_id Array of the group ids, where -1 represents galaxies not in a group.
#' @return A named list with pair properties.
#' @export
create_pair_catalog <- function(ra, dec, redshift, absolute_magnitudes, group_ids) .Call(wrap__create_pair_catalog, ra, dec, redshift, absolute_magnitudes, group_ids)

#' Completeness function to calculate the completeness at given positions.
#' @param ra_observed The Right Ascension of the galaxies that were observed, in degrees.
#' @param dec_observed The Declination of the galaxies in degrees that were observed, in degrees.
#' @param ra_target The Right Ascension of the galaxies that were targeted for observation in degrees.
#' @param dec_target The Declination of the galaxies that were targeted for observation in degress.
#' @param angular_radius The search area for each galaxy in degress.
#' @return An array of elements between 0-1.
#' @export
calc_completeness_rust <- function(ra_observed, dec_observed, ra_target, dec_target, angular_radius) .Call(wrap__calc_completeness_rust, ra_observed, dec_observed, ra_target, dec_target, angular_radius)


# nolint end
